# Generated by Django 3.0 on 2020-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
                'db_table': 'blacklist',
            },
        ),
    ]
