# Generated by Django 3.0 on 2020-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackdomain',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
