# Generated by Django 3.0 on 2020-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_auto_20200703_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('url', models.CharField(choices=[('-1', '不解析，跳转到原本网页'), ('0', '表示章节网页需要当前页面url拼接'), ('1', '表示章节链接使用本身自带的链接，不用拼接'), ('2', '用域名进行拼接')], max_length=10)),
                ('chapter_tag', models.CharField(max_length=10)),
                ('chapter_value', models.CharField(max_length=20)),
                ('content_tag', models.CharField(max_length=20)),
                ('content_value', models.CharField(max_length=20)),
            ],
        ),
    ]
