# Generated by Django 3.0 on 2020-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': '解析规则', 'verbose_name_plural': '解析规则'},
        ),
        migrations.AlterModelTable(
            name='rule',
            table='rule',
        ),
    ]
